require('my_plugins/for/editing/cmd-line')
require('my_plugins/for/editing/normal')
require('my_plugins/for/editing/windows-management')
-- require('my_plugins/for/editing/formatter')
require('my_plugins/for/editing/vim-abolish')
