require('my_plugins/for/git/fugitive')
require('my_plugins/for/git/fugitive-gitlab')
require('my_plugins/for/git/git-blame')
require('my_plugins/for/git/gitsigns')
require('my_plugins/for/git/trouble')
