require('my_plugins/for/uxui/cursorline')
require('my_plugins/for/uxui/colorscheme')
require('my_plugins/for/uxui/gutter')
require('my_plugins/for/uxui/notify')
require('my_plugins/for/uxui/nvim-web-devicons')
require('my_plugins/for/uxui/shade')
require('my_plugins/for/uxui/which-key')